name: Release UI Bundle Zip File
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version number of the release'
        required: true

jobs:
  build-ui-bundle:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version : '16'
    - name: Install gulp
      run: npm install -g gulp-cli
    - name: Install dependencies
      run: npm install
    - name: Build UI bundle
      run: gulp bundle
    - name: Add NOTICE file to build artifact
      run: |
        cd build
        mkdir esmf-antora-ui-bundle
        unzip ui-bundle.zip -d esmf-antora-ui-bundle
        cp ../legal/NOTICE-build.md ./esmf-antora-ui-bundle/NOTICE.md
        cd esmf-antora-ui-bundle
        zip esmf-antora-ui-bundle-${{ github.event.inputs.release_version  }}.zip -r *
        echo "Done with Zip"
        ls
    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      id: esmf_antora_ui_release
      with:
        body: "ESMF UI bundle for Antora in version v${{ github.event.inputs.release_version  }}. Intended for internal use within the ESMF."
        tag_name: v${{  github.event.inputs.release_version  }}
        draft: false
        prerelease: false
        files: build/esmf-antora-ui-bundle/esmf-antora-ui-bundle-${{ github.event.inputs.release_version }}.zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
